# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: NPM Package publish

on:
  release:
    types: [created]

jobs:
  publish-npm:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
      - name: "Automated Version Bump"
        uses: "phips28/gh-action-bump-version@master"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag-prefix: "v"
      - run: npm i --no-frozen-lockfile
      - run: npm run build
      - run: npm publish --no-git-checks --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_API_KEY }}
