# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: NPM Package bump version

on:
  push:
    branches:
      - "main"
    paths:
      - "package.json"
      - "rollup.config.ts"
      - "jest.config.ts"
      - "tsconfig.json"
      - "src/**/*"
      - ".github/workflows/npm-bump-version.yaml"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          ref: ${{ github.ref }}
      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
      - run: npm i --no-frozen-lockfile
      - name: "Test types"
        run: npm run test:types
      - name: "Test"
        run: npm run test
      - name: "Build"
        run: npm run build

  bump-version:
    permissions:
      contents: write
      id-token: write
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v5
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
      - name: "Automated Version Bump"
        uses: "phips28/gh-action-bump-version@master"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag-prefix: "v"
          default: prerelease
          preid: ${{ github.sha }}
